-- Generated by nwg-displays on 2026-06-06 at 00:51:52. Do not edit manually.

hl.monitor({
    output = "desc:Lenovo Group Limited 0x9156",
    mode = "1920x1200@60.0",
    position = "1438x9",
    scale = 1.5
})
hl.monitor({
    output = "desc:LG Electronics LG ULTRAFINE 509NTDVRA250",
    mode = "3840x2160@60.0",
    position = "0x0",
    scale = 2.67
})
hl.monitor({
    output = "desc:Lenovo Group Limited S27e-20 VNA6Z1RB",
    mode = "1920x1080@60.0",
    position = "2718x0",
    scale = 1.33
})
