-- Generated by nwg-displays on 2026-06-03 at 14:55:33. Do not edit manually.

hl.monitor({
    output = "desc:Lenovo Group Limited 0x9156",
    mode = "1920x1200@60.0",
    position = "1422x0",
    scale = 1.5
})
hl.monitor({
    output = "desc:LG Electronics LG ULTRAFINE 509NTDVRA250",
    mode = "3840x2160@60.0",
    position = "2702x0",
    scale = 2.7000000000000015
})
hl.monitor({
    output = "desc:Lenovo Group Limited S27e-20 VNA6Z1RB",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.35
})
